name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.14.4-otp-24

    steps:
    - uses: actions/checkout@v3

    - name: Install Hex
      run: mix local.hex --force

    - name: Install Rebar
      run: mix local.rebar --force           

    - name: Require dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile

    - name: Run tests
      run: mix test